[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/${INFURA_WEB3_KEY}"
linea = "https://linea-goerli.infura.io/v3/${INFURA_WEB3_KEY}"
alfajores = "https://celo-alfajores.infura.io/v3/${INFURA_WEB3_KEY}"
